# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: Getting Started
  items:
    - label: "How To Purchase RAM Token (Uniswap V2)"
      link: "getting-started/getting-started"
- label: Ram Token
  items:
    - label: "Whitepaper"
      link: "ram-token/white-paper"
    - label: "Torrent"
      link: "ram-token/torrent"
    - label: "The Responsive Dollar"
      link: "ram-token/the-responsive-dollar"
    - label: "A better Stablecoin"
      link: "ram-token/a-better-stablecoin"
    - label: "Injection Offering(IO)"
      link: "ram-token/injection-offering"
- label: Additional Information
  items:
    - label: "What are commodities?"
      link: "/additional-information/what-are-commodities"
    - label: "What are synthetic commodities?"
      link: "/additional-information/what-are-synthetic-commodities"
